# Automatically test the build as code is pushed to GitHub.
# This is the configuration file for Travis CI (travis-ci.org).

# Test on Ubuntu 20.04 Focal.
os: linux
dist: focal
language: cpp
compiler: g++
cache: ccache

# Install the required dependencies.
install: ./install-dependencies.sh

# Build and test.
script:
    - cmake . -DENABLE_UTESTS=ON
    - make -j $(getconf _NPROCESSORS_ONLN)
    - make test
    - python3 full_test.py

# Show ccache stats, clear for next time.
after_script:
    - ccache --show-stats
    - ccache --zero-stats
