name: tests

on: [pull_request, push, repository_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v2

    - name: install dependencies
      run: |
        ./install-dependencies.sh

    - name: build
      run: |
        cmake . -DENABLE_UTESTS=ON
        make -j $(getconf _NPROCESSORS_ONLN)

    - name: run unit tests
      run: make test

    - name: run functional test
      run: python3 full_test.py
