name: tests

on: [pull_request, push, repository_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      CCACHE_COMPRESS: "true"
      CCACHE_MAXSIZE: 500M

    steps:
    - name: checkout repository
      uses: actions/checkout@v2

    - name: install ccache
      run: sudo apt-get install ccache

    - name: identify machine architecture
      run: |
        gcc -### -E -march=native - &> machine-type.txt
        cat machine-type.txt

    - name: restore cache
      uses: actions/cache@v2
      with:
        path: ~/.ccache
        key: ccache-${{ hashFiles('machine-type.txt') }}-${{ github.sha }}
        restore-keys: ccache-${{ hashFiles('machine-type.txt') }}-

    - name: install dependencies
      run: |
        export PATH="/usr/lib/ccache:$PATH"
        ci-tests/install-dependencies.sh

    - name: build
      run: |
        export PATH="/usr/lib/ccache:$PATH"
        cmake . -DENABLE_UTESTS=ON -DENABLE_DET_UTESTS=ON
        make -j $(getconf _NPROCESSORS_ONLN)

    - name: show ccache stats
      run: |
        ccache --show-stats
        ccache --zero-stats

    - name: run unit tests
      run: make test

    - name: run functional test
      run: ci-tests/full_test.py
